#!/bin/bash
#usage: setup-vm goc48 ${WORKBUILDDIR} ${WORKSPACE}/tool_dir
#get oc client
echo $1 $2 $3
NODELABEL=$1
WORKBUILDDIR=$2
WORKDIR=$3
mkdir -p $WORKDIR
CURRENTDIR=`pwd`

http_proxy_tmp=${http_proxy}
https_proxy_tmp=${https_proxy}
if [[ "x${http_proxy}x" != "xx" ]] || [[ "x${https_proxy}x" != "xx" ]]; then
    echo "unset http_proxy https_proxy"
    unset http_proxy https_proxy
fi

sudo rm -rf /tmp/fixture-testdata-*
sudo rm -rf /tmp/ocp-*
rm -rf /tmp/*
podman rm -a -f
podman rmi -a -f
sudo rm -f /usr/bin/oc /usr/local/bin/oc /usr/local/bin/opm /usr/local/bin/initializer /usr/local/bin/configmap-server /usr/local/bin/registry-server /usr/bin/*operator*
export no_proxy=quay.io

cd /etc/pki/ca-trust/source/anchors
sudo curl -O --insecure https://certs.corp.redhat.com/certs/Current-IT-Root-CAs.pem
sudo curl -O --insecure https://engineering.redhat.com/Eng-CA.crt
sudo update-ca-trust extract
cd $WORKDIR

if echo $NODELABEL | grep -E '^goc([0-9]{2,3})$'; then
  NIGHTLYFLAG=$(echo $NODELABEL | tr -dc '0-9')
  echo $NIGHTLYFLAG
else
  echo "the node label is not correct. For example, goc45"
  exit 1
fi

sudo rm -f /etc/yum.repos.d/redhat_offcial.repo /etc/yum.repos.d/localdev-rhel-8-baseos-rpms.repo /etc/yum.repos.d/google-cloud-sdk.repo /etc/yum.repos.d/azure-cli.repo
sudo cp -f ${WORKBUILDDIR}/pipeline/repo-file/rhel9.3-baseos.repo /etc/yum.repos.d/rhel9.3-baseos.repo
sudo ls -lrt /etc/yum.repos.d/
sudo yum-config-manager --enable rhel9.3-baseos
sudo yum remove 'origin*.x86_64' 'atomic-openshift*.x86_64' 'openshift-clients*.x86_64' -y
#sudo yum -y install openshift-clients
sudo yum -y install jq patch docker sos zip unzip
sudo yum clean all -y
pip3 install requests
sos -h
#get oc client
echo "------------------get oc------------------------"
echo "get latest oc"
unset http_proxy https_proxy
curl -s -k -L https://mirror2.openshift.com/pub/openshift-v4/x86_64/clients/ocp-dev-preview/candidate-4.17/openshift-client-linux-amd64-rhel9.tar.gz -o oc-linux.tar.gz

tar -xzvf oc-linux.tar.gz
echo "get oc-linux.tar.gz successfully"
rm -f oc-linux.tar.gz
sudo mv oc /usr/local/bin/oc
if [[ "x${http_proxy_tmp}x" != "xx" ]] || [[ "x${https_proxy_tmp}x" != "xx" ]]; then
    echo "set env http_proxy https_proxy"
    export http_proxy=${http_proxy_tmp}
    export https_proxy=${https_proxy_tmp}
fi
echo "oc version:"
oc version
retVal=$?
if [ $retVal -ne 0 ]; then
    echo "install oc failed"
    exit 1
fi

echo "------------------get oc Done------------------------"

#get operatorSDK
#INSTALL_TOOLS Option filling rules
#If it contains a number, pull the PR from the downstream code. If it contains the string "upstream", pull the PR from the upstream code.
#example: operatorSDK:350 ; operatorSDK:upstream6619
if echo $INSTALL_TOOLS | grep -i 'operatorSDK' > /dev/null; then
    unset http_proxy https_proxy
    echo "------------------get operatorSDK------------------------"
    mkdir ${WORKSPACE}/osdk
    BUILD_CMD="make build"
    #get operatorsdk from upstream and upstreamversion is 1.39.1 for ocp4.19
    curl -s -k -L https://codeload.github.com/operator-framework/operator-sdk/tar.gz/refs/tags/v1.39.1 -o osdk.tar.gz
    mv osdk.tar.gz ${WORKSPACE}/osdk/
    cd ${WORKSPACE}/osdk/
    tar -xzf ${WORKSPACE}/osdk/osdk.tar.gz
    echo "get osdk.tar.gz successfully"
    rm -f ${WORKSPACE}/osdk/osdk.tar.gz
    cd ${WORKSPACE}/osdk/operator-sdk-1.39.1
    echo "buid command is [${BUILD_CMD}]"
    eval "${BUILD_CMD}"
    ls -lrt build/
    mv -f build/* $WORKDIR
    rm -fr ../osdk
    chown -R cloud-user:cloud-user $WORKDIR
    operator-sdk version
    cd $WORKDIR
    echo "------------------get operatorSDK Done------------------------"
else
    echo "skip get operatorSDK"
fi

#get ansibleplugin
if echo $INSTALL_TOOLS | grep -i 'ansible' > /dev/null; then
    unset http_proxy https_proxy
    echo "------------------get ansible------------------------"
    array=(${INSTALL_TOOLS//;/ })  
    for tool_name_index in ${array[@]}
    do
        if echo $tool_name_index | grep -i 'ansible' > /dev/null; then
            echo $tool_name_index
            echo "get ansible PR"
            PR=`echo $INSTALL_TOOLS | tr -cd "[0-9]"`
            echo "PR is ${PR}"
        fi
    done
#    buildansibleimage $PR $WORKDIR

    echo "get downstream code from PR ${PR} "
    mkdir ${WORKSPACE}/ansibleplugin
    git clone https://github.com/openshift/ansible-operator-plugins.git ${WORKSPACE}/ansibleplugin
    cd ${WORKSPACE}/ansibleplugin
    git remote add downstream https://github.com/openshift/ansible-operator-plugins.git
    git fetch downstream pull/${PR}/head:downstreamPR
    git checkout downstreamPR
    git status
    make build
    podman build --quiet -t quay.io/olmqe/ansible-operator-base:premergetest -f images/ansible-operator/Dockerfile .
    podman push quay.io/olmqe/ansible-operator-base:premergetest
    echo "build the ansible image finished"
    cd $WORKDIR
    export AnsiblePremergeTest="true"
    cd $WORKDIR
    echo "------------------get ansible Done------------------------"
else
    echo "skip get ansible"
    export AnsiblePremergeTest="false"
fi

#get helmplugin
if echo $INSTALL_TOOLS | grep -i 'helm' > /dev/null; then
    unset http_proxy https_proxy
    echo "------------------get helm------------------------"
    array=(${INSTALL_TOOLS//;/ })  
    for tool_name_index in ${array[@]}
    do
        if echo $tool_name_index | grep -i 'helm' > /dev/null; then
            echo $tool_name_index
            echo "get helm PR"
            PR=`echo $INSTALL_TOOLS | tr -cd "[0-9]"`
            echo "PR is ${PR}"
        fi
    done
#    buildhelmimage $PR $WORKDIR

    echo "get downstream code from PR ${PR} "
    mkdir ${WORKSPACE}/helm
    git clone https://github.com/openshift/ocp-release-operator-sdk.git ${WORKSPACE}/helm
    cd ${WORKSPACE}/helm
    git remote add downstream https://github.com/openshift/ocp-release-operator-sdk.git
    git fetch downstream pull/${PR}/head:downstreamPR
    git checkout downstreamPR
    git status
    sed -i 's#golang:1.22#quay.io/olmqe/golang:1.22#g' images/helm-operator/Dockerfile
    podman build --quiet -t quay.io/olmqe/helm-operator-base:premergetest -f images/helm-operator/Dockerfile .
    podman push quay.io/olmqe/helm-operator-base:premergetest
    echo "build the helm image finished"
    cd $WORKDIR
    export HelmPremergeTest="true"
    cd $WORKDIR
    echo "------------------get helm Done------------------------"
else
    echo "skip get helm"
    export HelmPremergeTest="false"
fi

#get hypershift
if echo $INSTALL_TOOLS | grep -i 'hypershift' > /dev/null; then
    unset http_proxy https_proxy
    echo "------------------get hypershift------------------------"
    oc image extract quay.io/openshifttest/hypershift-client:latest --file=/hypershift
    mv -f hypershift $WORKDIR
    chmod 755 $WORKDIR/hypershift
    chown -R cloud-user:cloud-user $WORKDIR
    hypershift -h
else
    echo "skip get hypershift"
fi


#get opm client
if echo $INSTALL_TOOLS | grep -i 'opm' > /dev/null; then
    echo "------------------get opm------------------------"
    echo "get latest opm"
    echo "set env http_proxy https_proxy"
    unset http_proxy https_proxy
    BRANCH="release-${NIGHTLYFLAG:0:1}.${NIGHTLYFLAG:1}"
    mkdir ${WORKSPACE}/operator-framework-olm
    git clone --depth=1 git@github.com:openshift/operator-framework-olm.git ${WORKSPACE}/operator-framework-olm --branch ${BRANCH}
    cd ${WORKSPACE}/operator-framework-olm
    make bin/opm
    mv -f bin/opm $WORKDIR
    cd ${WORKSPACE}
    echo "opm version:"
    opm version
    retVal=$?
    if [ $retVal -ne 0 ]; then
        echo "get opm failed"
        exit 1
    fi
fi

rm -rf ${XDG_RUNTIME_DIR}/containers/auth.json
cp -f ~/.docker/auto/config.json ~/.docker
podman login quay.io
cd $CURRENTDIR
output=`sudo podman ps -a`
if [[ $output == *"0.0.0.0:5000"* ]]; then
  echo "registry is up"
else
  echo "run /home/cloud-user/jian/auto_run_registry.sh"
  /home/cloud-user/jian/auto_run_registry.sh
fi

if [ ! -f "/root/kustomize" ]; then
    echo "install kustomize"
    sudo wget "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"
    sudo chmod +x install_kustomize.sh
    sudo ./install_kustomize.sh 3.8.7 /root
fi

if [[ "x${http_proxy_tmp}x" != "xx" ]] || [[ "x${https_proxy_tmp}x" != "xx" ]]; then
    echo "set env http_proxy https_proxy"
    export http_proxy=${http_proxy_tmp}
    export https_proxy=${https_proxy_tmp}
fi
